//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MFCApplication3.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MFCApplication3TYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_EXPLORER1                   307
#define IDD_DIALOG_NEWSLU               310
#define IDD_EVENTVIEW                   312
#define IDD_PREEVENTVIEW                314
#define IDD_DIALOG_NEW_SLU              315
#define IDD_EVENT_LOADMUSIC             316
#define IDR_POPUP_EXPLORER1             318
#define IDC_TREE1                       1000
#define IDC_LIST1                       1001
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON2                     1005
#define IDC_31                          1006
#define IDC_BUTTON3                     1006
#define IDC_BUTTON4                     1007
#define IDC_BUTTON5                     1008
#define IDC_BUTTON6                     1009
#define IDC_BUTTON7                     1010
#define IDC_BUTTON8                     1011
#define IDC_BUTTON9                     1012
#define IDC_BUTTON10                    1013
#define IDC_BUTTON11                    1014
#define IDC_BUTTON12                    1015
#define IDC_BUTTON13                    1016
#define IDC_BUTTON14                    1017
#define IDC_BUTTON15                    1018
#define IDC_BUTTON16                    1019
#define IDC_BUTTON17                    1020
#define IDC_BUTTON18                    1021
#define IDC_BUTTON19                    1022
#define IDC_BUTTON20                    1023
#define IDC_BUTTON21                    1024
#define IDC_BUTTON22                    1025
#define IDC_BUTTON23                    1026
#define IDC_BUTTON24                    1027
#define IDC_BUTTON25                    1028
#define IDC_BUTTON26                    1029
#define IDC_BUTTON27                    1030
#define IDC_BUTTON28                    1031
#define IDC_COMBO1                      1032
#define IDC_LIST_INFO                   1033
#define IDC_LIST_CODE                   1034
#define IDC_LIST_PRE_INFO               1035
#define IDC_LIST_PRE_CODE               1036
#define IDC_GROUP_CHAR                  1037
#define IDC_COMBO2                      1038
#define IDC_COMBO3                      1039
#define IDC_STATIC1                     1040
#define IDC_STATIC2                     1041
#define IDC_STATIC4                     1042
#define IDC_STATIC5                     1043
#define IDC_GROUP_LOCA                  1044
#define IDC_GROUP_TURN                  1045
#define IDC_GROUP_MISC                  1046
#define IDC_STATIC9                     1047
#define IDC_STATIC10                    1048
#define IDC_RADIO1                      1049
#define IDC_RADIO2                      1050
#define IDC_RADIO3                      1051
#define IDC_RADIO4                      1052
#define IDC_RADIO5                      1053
#define IDC_RADIO6                      1054
#define IDC_GROUP_TURN2                 1055
#define IDC_COMBO4                      1056
#define IDC_COMBO5                      1057
#define IDC_COMBO6                      1058
#define IDC_COMBO7                      1059
#define IDC_EDIT4                       1060
#define IDC_EDIT5                       1061
#define IDC_GROUP_MISC2                 1062
#define IDC_COMBO8                      1063
#define IDC_RADIO7                      1064
#define IDC_RADIO8                      1065
#define IDC_RADIO9                      1066
#define IDC_STATIC12                    1067
#define IDC_STATIC13                    1068
#define IDC_STATIC14                    1069
#define IDC_STATIC17                    1070
#define IDC_COMBO9                      1072
#define IDC_COMBO10                     1073
#define IDC_EDIT8                       1074
#define IDC_EDIT9                       1075
#define IDC_EDIT10                      1076
#define IDC_EDIT11                      1077
#define IDC_COMBO11                     1078
#define IDC_STATIC18                    1079
#define IDC_STATIC19                    1080
#define IDC_STATIC21                    1081
#define IDC_STATIC22                    1082
#define IDC_STATIC23                    1083
#define IDC_STATIC24                    1084
#define IDC_STATIC25                    1085
#define IDR_EVENTTYPE                   1501
#define IDR_PREEVENTTYPE                1502
#define ID_SLU_NEW                      32777
#define ID_SLU_CLOSE                    32779
#define ID_SLU_OPEN                     32780
#define ID_SLU_MRU_SLU1                 32781
#define ID_SLU_SAVE                     32788
#define ID_32790                        32790
#define ID_EDIT_REMOVE                  32791
#define ID_32792                        32792
#define ID_POPUP_EXPLORER_CREATNEWFILE  32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           315
#endif
#endif
